### ISSUE TITLE
Hi !! just what I was looking for ... but have some errors ... any ideas? "Error when evaluating SSR"

### ISSUE THREAD

**Issue by aktxyz** [galkatz373/svelte-apexcharts#125]
```
8:49:33 PM [vite] Error when evaluating SSR module /node_modules/svelte-apexcharts/src/index.js:
ReferenceError: window is not defined
    at Object.<anonymous> (xxx\app\node_modules\apexcharts\dist\apexcharts.common.js:6:345884)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at nodeRequire (xxx\app\node_modules\vite\dist\node\chunks\dep-e9a16784.js:68211:17)
    at ssrImport (xxx\app\node_modules\vite\dist\node\chunks\dep-e9a16784.js:68164:20)
    at eval (/node_modules/svelte-apexcharts/src/index.js:3:31)
```

**Comment by aktxyz** [comment]
nm ... found this 

https://www.reddit.com/r/sveltejs/comments/n508th/apex_chart_with_sveltekit/gx74djr/
